export const AIRLINES = [
  "AA - American Airlines",
  "AC - Air Canada",
  "AE - American Eagle",
  "AF - Air France",
  "AG - Allegiant",
  "AI - Air India",
  "AK - Alaska",
  "AL - Aer Lingus",
  "AM - AeroMexico",
  "AN - Air New Zealand",
  "AO - Aeroflot",
  "AR - Air Transat",
  "AS - Air Serbia",
  "AT - AirTran",
  "ATA - American Trans Air",
  "AU - Austrian Airlines",
  "AV - Avianca",
  "AW - America West",
  "BA - British Airways",
  "BH - Bahamasair",
  "BS - Big Sky",
  "CA - Corporate Airlines",
  "CM - Com-Air",
  "CN - Canadian Airlines",
  "CO - Continental",
  "CP - Copa Airlines",
  "DA - Domodedovo Airlines",
  "DL - Delta",
  "EJ - Express Jet",
  "EK - Emirates",
  "FT - Frontier",
  "GA - Grenadine Air Alliance",
  "GL - Great Lakes",
  "HA - Horizon Airlines",
  "HI - Hawaiian Airlines",
  "IA - Island Air",
  "IC - Iceland Air",
  "JB - JetBlue Airways",
  "KLM - KLM Royal Dutch Airlines",
  "LH - Lufhansa",
  "LT - Liat Airlines",
  "ME - Midway",
  "MS - Mesaba",
  "MU - Mustique Airways",
  "MW - Midwest",
  "MX - Mexicana",
  "NA - National",
  "NW - Northwest",
  "OC - One Caribbean",
  "QA - Qantas",
  "RA - Ravn Alaska",
  "SA - South African",
  "SC - SunCountry",
  "SK - Skywest",
  "SM - Skyway",
  "SN - Scandinavian",
  "SP - Spirit",
  "SVG - SVG Air",
  "SW - Southwest",
  "TA - Tropic Air",
  "TK - Turkish Airlines",
  "TWA - TransWorld Air",
  "UN - United",
  "US - US Airways",
  "VA - Vanguard",
  "VG - Virgin America",
  "VL - Volaris Airlines",
  "WJ - West Jet",
  "US - US Aiways",
  "SAE - Southern Airways Express",
  "Qatar Airways",
];

export const COUNTRIES = [
  "Argentina",
  "Australia",
  "Azerbaijan",
  "Bahamas",
  "Belize",
  "Brazil",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Dominican Republic",
  "Ecuador",
  "El Salvador",
  "Germany",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guyana",
  "Honduras",
  "India",
  "Israel",
  "Jamaica",
  "Kuwait",
  "Mauritius",
  "Mexico",
  "Nicaragua",
  "Paraguay",
  "Peru",
  "Philippines",
  "Serbia",
  "South Africa",
  "Tajikistan",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Kingdom",
  "United States",
];
