export interface PassengerData {
  id: string;
  createdTime: string;
  Type: string;
  "First Name": string;
  "Last Name": string;
  "Date of Birth": string;
  Gender: string;
  Street: string;
  Country: string;
  Email: string;
  "Household Income": number;
  "Household Size": number;
  Ethnicity: string[];
  "Military Service": string;
  "Military Member": string[];
  "How did you hear about us": string[];
  "All Flight Legs": string[];
  Diagnoses: string[];
  "AirTable Record ID": string;
  "# of Flight Legs": number;
  "# of Booked Flight Requests": number;
  "Birth Month": string;
  "Full Name": string;
  "Passenger Names (from All Flight Legs)": string[];
  Age: number;
  "Latest Trip": string;
  Notes?: string;
  "Relationship": string[];
}
